// Visual step-by-step demo tutorial for SQL Payroll support onboarding.
// Every page of every KB guide's PDF is included here as a real screenshot,
// rendered from the official sql.com.my PDFs (see the Notion 'SQL Payroll
// Knowledge Base' for sources) — by design, not trimmed down, so this is a
// long, thorough walkthrough rather than a quick summary.

export const DEMO_STEPS = {
  1: {
    topic: "Getting Started & Employee Setup",
    goal: "The new hire understands the Payroll module and can set up a company and an employee from scratch.",
    lessons: [
      {
        title: "Maintain Payroll Company Profile",
        steps: [
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page1.jpg", caption: "Open the company payroll profile and fill in the legal company name, registration number, and address.", explanation: "These details flow onto every payslip, EA form, and statutory submission generated later — errors here cascade into every downstream document." },
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page2.jpg", caption: "Page 2 of 12." },
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page3.jpg", caption: "Page 3 of 12." },
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page4.jpg", caption: "Page 4 of 12." },
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page5.jpg", caption: "Page 5 of 12." },
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page6.jpg", caption: "Page 6 of 12." },
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page7.jpg", caption: "Page 7 of 12." },
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page8.jpg", caption: "Page 8 of 12." },
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page9.jpg", caption: "Page 9 of 12." },
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page10.jpg", caption: "Page 10 of 12." },
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page11.jpg", caption: "Page 11 of 12." },
          { image: "assets/tutorials/day1/maintain-payroll-company-profile/page12.jpg", caption: "Page 12 of 12." },
        ],
      },
      {
        title: "SQL Payroll User Guide",
        steps: [
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page1.jpg", caption: "SQL Payroll User Guide — page 1 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page2.jpg", caption: "Page 2 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page3.jpg", caption: "Page 3 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page4.jpg", caption: "Page 4 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page5.jpg", caption: "Page 5 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page6.jpg", caption: "Page 6 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page7.jpg", caption: "Page 7 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page8.jpg", caption: "Page 8 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page9.jpg", caption: "Page 9 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page10.jpg", caption: "Page 10 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page11.jpg", caption: "Page 11 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page12.jpg", caption: "Page 12 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page13.jpg", caption: "Page 13 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page14.jpg", caption: "Page 14 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page15.jpg", caption: "Page 15 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page16.jpg", caption: "Page 16 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page17.jpg", caption: "Page 17 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page18.jpg", caption: "Page 18 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page19.jpg", caption: "Page 19 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page20.jpg", caption: "Page 20 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page21.jpg", caption: "Page 21 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page22.jpg", caption: "Page 22 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page23.jpg", caption: "Page 23 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page24.jpg", caption: "Page 24 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page25.jpg", caption: "Page 25 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page26.jpg", caption: "Page 26 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page27.jpg", caption: "Page 27 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page28.jpg", caption: "Page 28 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page29.jpg", caption: "Page 29 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page30.jpg", caption: "Page 30 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page31.jpg", caption: "Page 31 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page32.jpg", caption: "Page 32 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page33.jpg", caption: "Page 33 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page34.jpg", caption: "Page 34 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page35.jpg", caption: "Page 35 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page36.jpg", caption: "Page 36 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page37.jpg", caption: "Page 37 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page38.jpg", caption: "Page 38 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page39.jpg", caption: "Page 39 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page40.jpg", caption: "Page 40 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page41.jpg", caption: "Page 41 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page42.jpg", caption: "Page 42 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page43.jpg", caption: "Page 43 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page44.jpg", caption: "Page 44 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page45.jpg", caption: "Page 45 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page46.jpg", caption: "Page 46 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page47.jpg", caption: "Page 47 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page48.jpg", caption: "Page 48 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page49.jpg", caption: "Page 49 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page50.jpg", caption: "Page 50 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page51.jpg", caption: "Page 51 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page52.jpg", caption: "Page 52 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page53.jpg", caption: "Page 53 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page54.jpg", caption: "Page 54 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page55.jpg", caption: "Page 55 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page56.jpg", caption: "Page 56 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page57.jpg", caption: "Page 57 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page58.jpg", caption: "Page 58 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page59.jpg", caption: "Page 59 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page60.jpg", caption: "Page 60 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page61.jpg", caption: "Page 61 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page62.jpg", caption: "Page 62 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page63.jpg", caption: "Page 63 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page64.jpg", caption: "Page 64 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page65.jpg", caption: "Page 65 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page66.jpg", caption: "Page 66 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page67.jpg", caption: "Page 67 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page68.jpg", caption: "Page 68 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page69.jpg", caption: "Page 69 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page70.jpg", caption: "Page 70 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page71.jpg", caption: "Page 71 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page72.jpg", caption: "Page 72 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page73.jpg", caption: "Page 73 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page74.jpg", caption: "Page 74 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page75.jpg", caption: "Page 75 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page76.jpg", caption: "Page 76 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page77.jpg", caption: "Page 77 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page78.jpg", caption: "Page 78 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page79.jpg", caption: "Page 79 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page80.jpg", caption: "Page 80 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page81.jpg", caption: "Page 81 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page82.jpg", caption: "Page 82 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page83.jpg", caption: "Page 83 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page84.jpg", caption: "Page 84 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page85.jpg", caption: "Page 85 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page86.jpg", caption: "Page 86 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page87.jpg", caption: "Page 87 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page88.jpg", caption: "Page 88 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page89.jpg", caption: "Page 89 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page90.jpg", caption: "Page 90 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page91.jpg", caption: "Page 91 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page92.jpg", caption: "Page 92 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page93.jpg", caption: "Page 93 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page94.jpg", caption: "Page 94 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page95.jpg", caption: "Page 95 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page96.jpg", caption: "Page 96 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page97.jpg", caption: "Page 97 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page98.jpg", caption: "Page 98 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page99.jpg", caption: "Page 99 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page100.jpg", caption: "Page 100 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page101.jpg", caption: "Page 101 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page102.jpg", caption: "Page 102 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page103.jpg", caption: "Page 103 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page104.jpg", caption: "Page 104 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page105.jpg", caption: "Page 105 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page106.jpg", caption: "Page 106 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page107.jpg", caption: "Page 107 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page108.jpg", caption: "Page 108 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page109.jpg", caption: "Page 109 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page110.jpg", caption: "Page 110 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page111.jpg", caption: "Page 111 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page112.jpg", caption: "Page 112 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page113.jpg", caption: "Page 113 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page114.jpg", caption: "Page 114 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page115.jpg", caption: "Page 115 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page116.jpg", caption: "Page 116 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page117.jpg", caption: "Page 117 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page118.jpg", caption: "Page 118 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page119.jpg", caption: "Page 119 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page120.jpg", caption: "Page 120 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page121.jpg", caption: "Page 121 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page122.jpg", caption: "Page 122 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page123.jpg", caption: "Page 123 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page124.jpg", caption: "Page 124 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page125.jpg", caption: "Page 125 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page126.jpg", caption: "Page 126 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page127.jpg", caption: "Page 127 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page128.jpg", caption: "Page 128 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page129.jpg", caption: "Page 129 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page130.jpg", caption: "Page 130 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page131.jpg", caption: "Page 131 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page132.jpg", caption: "Page 132 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page133.jpg", caption: "Page 133 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page134.jpg", caption: "Page 134 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page135.jpg", caption: "Page 135 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page136.jpg", caption: "Page 136 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page137.jpg", caption: "Page 137 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page138.jpg", caption: "Page 138 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page139.jpg", caption: "Page 139 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page140.jpg", caption: "Page 140 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page141.jpg", caption: "Page 141 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page142.jpg", caption: "Page 142 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page143.jpg", caption: "Page 143 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page144.jpg", caption: "Page 144 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page145.jpg", caption: "Page 145 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page146.jpg", caption: "Page 146 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page147.jpg", caption: "Page 147 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page148.jpg", caption: "Page 148 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page149.jpg", caption: "Page 149 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page150.jpg", caption: "Page 150 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page151.jpg", caption: "Page 151 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page152.jpg", caption: "Page 152 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page153.jpg", caption: "Page 153 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page154.jpg", caption: "Page 154 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page155.jpg", caption: "Page 155 of 156." },
          { image: "assets/tutorials/day1/sql-payroll-user-guide/page156.jpg", caption: "Page 156 of 156." },
        ],
      },
      {
        title: "Employment Contract - Stamp Duty",
        steps: [
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page1.jpg", caption: "Employment Contract - Stamp Duty — page 1 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page2.jpg", caption: "Page 2 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page3.jpg", caption: "Page 3 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page4.jpg", caption: "Page 4 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page5.jpg", caption: "Page 5 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page6.jpg", caption: "Page 6 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page7.jpg", caption: "Page 7 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page8.jpg", caption: "Page 8 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page9.jpg", caption: "Page 9 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page10.jpg", caption: "Page 10 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page11.jpg", caption: "Page 11 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page12.jpg", caption: "Page 12 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page13.jpg", caption: "Page 13 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page14.jpg", caption: "Page 14 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page15.jpg", caption: "Page 15 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page16.jpg", caption: "Page 16 of 17." },
          { image: "assets/tutorials/day1/employment-contract-stamp-duty/page17.jpg", caption: "Page 17 of 17." },
        ],
      },
      {
        title: "Maintain Employee",
        steps: [
          { image: "assets/tutorials/day1/maintain-employee/page1.jpg", caption: "Add a new employee record: personal info, IC number, employment date, and basic salary.", explanation: "This is the master record every other Payroll screen (wages, contributions, payment method) reads from." },
          { image: "assets/tutorials/day1/maintain-employee/page2.jpg", caption: "Page 2 of 8." },
          { image: "assets/tutorials/day1/maintain-employee/page3.jpg", caption: "Page 3 of 8." },
          { image: "assets/tutorials/day1/maintain-employee/page4.jpg", caption: "Page 4 of 8." },
          { image: "assets/tutorials/day1/maintain-employee/page5.jpg", caption: "Page 5 of 8." },
          { image: "assets/tutorials/day1/maintain-employee/page6.jpg", caption: "Page 6 of 8." },
          { image: "assets/tutorials/day1/maintain-employee/page7.jpg", caption: "Page 7 of 8." },
          { image: "assets/tutorials/day1/maintain-employee/page8.jpg", caption: "Page 8 of 8." },
        ],
      },
      {
        title: "Maintain Employee using MyKad Reader",
        steps: [
          { image: "assets/tutorials/day1/maintain-employee-using-mykad-reader/page1.jpg", caption: "Scan the employee's MyKad to auto-populate name and IC number instead of typing them manually.", explanation: "Saves time and reduces data-entry errors for high-volume hiring, but always let the client verify the scanned fields before saving." },
          { image: "assets/tutorials/day1/maintain-employee-using-mykad-reader/page2.jpg", caption: "Page 2 of 3." },
          { image: "assets/tutorials/day1/maintain-employee-using-mykad-reader/page3.jpg", caption: "Page 3 of 3." },
        ],
      },
      {
        title: "Payroll Bulk Email with Password",
        steps: [
          { image: "assets/tutorials/day1/payroll-bulk-email-with-password/page1.jpg", caption: "Payroll Bulk Email with Password — page 1 of 5." },
          { image: "assets/tutorials/day1/payroll-bulk-email-with-password/page2.jpg", caption: "Page 2 of 5." },
          { image: "assets/tutorials/day1/payroll-bulk-email-with-password/page3.jpg", caption: "Page 3 of 5." },
          { image: "assets/tutorials/day1/payroll-bulk-email-with-password/page4.jpg", caption: "Page 4 of 5." },
          { image: "assets/tutorials/day1/payroll-bulk-email-with-password/page5.jpg", caption: "Page 5 of 5." },
        ],
      },
      {
        title: "Print Appointment Confirmation Increment Letter",
        steps: [
          { image: "assets/tutorials/day1/print-appointment-confirmation-increment-letter/page1.jpg", caption: "Generate an Appointment Letter once the new hire's record is saved.", explanation: "Confirmation and Increment letters use the same feature later in the employee's lifecycle — worth knowing they're one shared tool, not three separate ones." },
          { image: "assets/tutorials/day1/print-appointment-confirmation-increment-letter/page2.jpg", caption: "Page 2 of 3." },
          { image: "assets/tutorials/day1/print-appointment-confirmation-increment-letter/page3.jpg", caption: "Page 3 of 3." },
        ],
      },
    ],
    practiceTask: "In the demo company, complete the company payroll profile (EPF/SOCSO/EIS/PCB employer numbers), add a new employee record, and print an appointment letter.",
  },
  2: {
    topic: "Leave & HR Modules",
    goal: "The new hire can answer the most common leave and HR self-service questions.",
    lessons: [
      {
        title: "Leave Module",
        steps: [
          { image: "assets/tutorials/day2/leave-module/page1.jpg", caption: "Define a leave type (e.g. Annual, Medical) and set its entitlement rules.", explanation: "This is the rulebook every other leave feature — brought-forward balances, hourly leave, E-Leave — builds on top of." },
          { image: "assets/tutorials/day2/leave-module/page2.jpg", caption: "Page 2 of 15." },
          { image: "assets/tutorials/day2/leave-module/page3.jpg", caption: "Page 3 of 15." },
          { image: "assets/tutorials/day2/leave-module/page4.jpg", caption: "Page 4 of 15." },
          { image: "assets/tutorials/day2/leave-module/page5.jpg", caption: "Page 5 of 15." },
          { image: "assets/tutorials/day2/leave-module/page6.jpg", caption: "Page 6 of 15." },
          { image: "assets/tutorials/day2/leave-module/page7.jpg", caption: "Page 7 of 15." },
          { image: "assets/tutorials/day2/leave-module/page8.jpg", caption: "Page 8 of 15." },
          { image: "assets/tutorials/day2/leave-module/page9.jpg", caption: "Page 9 of 15." },
          { image: "assets/tutorials/day2/leave-module/page10.jpg", caption: "Page 10 of 15." },
          { image: "assets/tutorials/day2/leave-module/page11.jpg", caption: "Page 11 of 15." },
          { image: "assets/tutorials/day2/leave-module/page12.jpg", caption: "Page 12 of 15." },
          { image: "assets/tutorials/day2/leave-module/page13.jpg", caption: "Page 13 of 15." },
          { image: "assets/tutorials/day2/leave-module/page14.jpg", caption: "Page 14 of 15." },
          { image: "assets/tutorials/day2/leave-module/page15.jpg", caption: "Page 15 of 15." },
        ],
      },
      {
        title: "Brought Forward Leave",
        steps: [
          { image: "assets/tutorials/day2/brought-forward-leave/page1.jpg", caption: "Run the Brought Forward Leave process at the start of a new leave year to carry over unused balances.", explanation: "This doesn't happen automatically — it's a process the client (or support agent) must run. A '0 balance' complaint right after year-end is almost always a missed run here." },
          { image: "assets/tutorials/day2/brought-forward-leave/page2.jpg", caption: "Page 2 of 8." },
          { image: "assets/tutorials/day2/brought-forward-leave/page3.jpg", caption: "Page 3 of 8." },
          { image: "assets/tutorials/day2/brought-forward-leave/page4.jpg", caption: "Page 4 of 8." },
          { image: "assets/tutorials/day2/brought-forward-leave/page5.jpg", caption: "Page 5 of 8." },
          { image: "assets/tutorials/day2/brought-forward-leave/page6.jpg", caption: "Page 6 of 8." },
          { image: "assets/tutorials/day2/brought-forward-leave/page7.jpg", caption: "Page 7 of 8." },
          { image: "assets/tutorials/day2/brought-forward-leave/page8.jpg", caption: "Page 8 of 8." },
        ],
      },
      {
        title: "How to Make Leave Apply as Hourly Time",
        steps: [
          { image: "assets/tutorials/day2/how-to-make-leave-apply-as-hourly-time/page1.jpg", caption: "Switch a leave type's application unit from full/half day to hours.", explanation: "Useful for shift-based staff taking partial-day leave — the conversion rate against normal working hours matters if a deduction looks off." },
          { image: "assets/tutorials/day2/how-to-make-leave-apply-as-hourly-time/page2.jpg", caption: "Page 2 of 3." },
          { image: "assets/tutorials/day2/how-to-make-leave-apply-as-hourly-time/page3.jpg", caption: "Page 3 of 3." },
        ],
      },
      {
        title: "E Claim Setup User Guide",
        steps: [
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page1.jpg", caption: "E Claim Setup User Guide — page 1 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page2.jpg", caption: "Page 2 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page3.jpg", caption: "Page 3 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page4.jpg", caption: "Page 4 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page5.jpg", caption: "Page 5 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page6.jpg", caption: "Page 6 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page7.jpg", caption: "Page 7 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page8.jpg", caption: "Page 8 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page9.jpg", caption: "Page 9 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page10.jpg", caption: "Page 10 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page11.jpg", caption: "Page 11 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page12.jpg", caption: "Page 12 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page13.jpg", caption: "Page 13 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page14.jpg", caption: "Page 14 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page15.jpg", caption: "Page 15 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page16.jpg", caption: "Page 16 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page17.jpg", caption: "Page 17 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page18.jpg", caption: "Page 18 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page19.jpg", caption: "Page 19 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page20.jpg", caption: "Page 20 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page21.jpg", caption: "Page 21 of 22." },
          { image: "assets/tutorials/day2/e-claim-setup-user-guide/page22.jpg", caption: "Page 22 of 22." },
        ],
      },
      {
        title: "E Leave Setup User Guide",
        steps: [
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page1.jpg", caption: "Enable the E-Leave employee self-service portal and confirm it syncs against the Leave Module rules just configured.", explanation: "E-Leave is the employee-facing layer; the rules underneath still live in the Leave Module. A sync issue here shows up as 'my balance online looks wrong.'" },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page2.jpg", caption: "Page 2 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page3.jpg", caption: "Page 3 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page4.jpg", caption: "Page 4 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page5.jpg", caption: "Page 5 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page6.jpg", caption: "Page 6 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page7.jpg", caption: "Page 7 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page8.jpg", caption: "Page 8 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page9.jpg", caption: "Page 9 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page10.jpg", caption: "Page 10 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page11.jpg", caption: "Page 11 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page12.jpg", caption: "Page 12 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page13.jpg", caption: "Page 13 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page14.jpg", caption: "Page 14 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page15.jpg", caption: "Page 15 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page16.jpg", caption: "Page 16 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page17.jpg", caption: "Page 17 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page18.jpg", caption: "Page 18 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page19.jpg", caption: "Page 19 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page20.jpg", caption: "Page 20 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page21.jpg", caption: "Page 21 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page22.jpg", caption: "Page 22 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page23.jpg", caption: "Page 23 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page24.jpg", caption: "Page 24 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page25.jpg", caption: "Page 25 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page26.jpg", caption: "Page 26 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page27.jpg", caption: "Page 27 of 28." },
          { image: "assets/tutorials/day2/e-leave-setup-user-guide/page28.jpg", caption: "Page 28 of 28." },
        ],
      },
      {
        title: "E Payroll Sync Payslip EA Form",
        steps: [
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page1.jpg", caption: "E Payroll Sync Payslip EA Form — page 1 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page2.jpg", caption: "Page 2 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page3.jpg", caption: "Page 3 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page4.jpg", caption: "Page 4 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page5.jpg", caption: "Page 5 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page6.jpg", caption: "Page 6 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page7.jpg", caption: "Page 7 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page8.jpg", caption: "Page 8 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page9.jpg", caption: "Page 9 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page10.jpg", caption: "Page 10 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page11.jpg", caption: "Page 11 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page12.jpg", caption: "Page 12 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page13.jpg", caption: "Page 13 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page14.jpg", caption: "Page 14 of 15." },
          { image: "assets/tutorials/day2/e-payroll-sync-payslip-ea-form/page15.jpg", caption: "Page 15 of 15." },
        ],
      },
      {
        title: "E TMS Setup User Guide",
        steps: [
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page1.jpg", caption: "E TMS Setup User Guide — page 1 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page2.jpg", caption: "Page 2 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page3.jpg", caption: "Page 3 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page4.jpg", caption: "Page 4 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page5.jpg", caption: "Page 5 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page6.jpg", caption: "Page 6 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page7.jpg", caption: "Page 7 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page8.jpg", caption: "Page 8 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page9.jpg", caption: "Page 9 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page10.jpg", caption: "Page 10 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page11.jpg", caption: "Page 11 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page12.jpg", caption: "Page 12 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page13.jpg", caption: "Page 13 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page14.jpg", caption: "Page 14 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page15.jpg", caption: "Page 15 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page16.jpg", caption: "Page 16 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page17.jpg", caption: "Page 17 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page18.jpg", caption: "Page 18 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page19.jpg", caption: "Page 19 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page20.jpg", caption: "Page 20 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page21.jpg", caption: "Page 21 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page22.jpg", caption: "Page 22 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page23.jpg", caption: "Page 23 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page24.jpg", caption: "Page 24 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page25.jpg", caption: "Page 25 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page26.jpg", caption: "Page 26 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page27.jpg", caption: "Page 27 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page28.jpg", caption: "Page 28 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page29.jpg", caption: "Page 29 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page30.jpg", caption: "Page 30 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page31.jpg", caption: "Page 31 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page32.jpg", caption: "Page 32 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page33.jpg", caption: "Page 33 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page34.jpg", caption: "Page 34 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page35.jpg", caption: "Page 35 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page36.jpg", caption: "Page 36 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page37.jpg", caption: "Page 37 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page38.jpg", caption: "Page 38 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page39.jpg", caption: "Page 39 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page40.jpg", caption: "Page 40 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page41.jpg", caption: "Page 41 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page42.jpg", caption: "Page 42 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page43.jpg", caption: "Page 43 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page44.jpg", caption: "Page 44 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page45.jpg", caption: "Page 45 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page46.jpg", caption: "Page 46 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page47.jpg", caption: "Page 47 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page48.jpg", caption: "Page 48 of 49." },
          { image: "assets/tutorials/day2/e-tms-setup-user-guide/page49.jpg", caption: "Page 49 of 49." },
        ],
      },
      {
        title: "HRMS Payroll setup user guide",
        steps: [
          { image: "assets/tutorials/day2/hrms-payroll-setup-user-guide/page1.jpg", caption: "HRMS Payroll setup user guide — page 1 of 8." },
          { image: "assets/tutorials/day2/hrms-payroll-setup-user-guide/page2.jpg", caption: "Page 2 of 8." },
          { image: "assets/tutorials/day2/hrms-payroll-setup-user-guide/page3.jpg", caption: "Page 3 of 8." },
          { image: "assets/tutorials/day2/hrms-payroll-setup-user-guide/page4.jpg", caption: "Page 4 of 8." },
          { image: "assets/tutorials/day2/hrms-payroll-setup-user-guide/page5.jpg", caption: "Page 5 of 8." },
          { image: "assets/tutorials/day2/hrms-payroll-setup-user-guide/page6.jpg", caption: "Page 6 of 8." },
          { image: "assets/tutorials/day2/hrms-payroll-setup-user-guide/page7.jpg", caption: "Page 7 of 8." },
          { image: "assets/tutorials/day2/hrms-payroll-setup-user-guide/page8.jpg", caption: "Page 8 of 8." },
        ],
      },
    ],
    practiceTask: "Configure a leave type with a brought-forward balance, set up E-Leave for the demo employee, and apply a leave request in hourly units.",
  },
  3: {
    topic: "Payroll Processing",
    goal: "The new hire can run a standard monthly payroll and handle common additions (OT, commission, advances, bonus).",
    lessons: [
      {
        title: "Maintain Wages",
        steps: [
          { image: "assets/tutorials/day3/maintain-wages/page1.jpg", caption: "Set the employee's basic wage structure in Maintain Wages.", explanation: "This is the base figure every payroll run calculates from — get this wrong and everything downstream is wrong too." },
          { image: "assets/tutorials/day3/maintain-wages/page2.jpg", caption: "Page 2 of 2." },
        ],
      },
      {
        title: "Payroll Frequency Method",
        steps: [
          { image: "assets/tutorials/day3/payroll-frequency-method/page1.jpg", caption: "Confirm the company's Payroll Frequency Method (monthly, bi-monthly, weekly).", explanation: "Determines how often a run happens — worth confirming before processing the first run for a new client." },
          { image: "assets/tutorials/day3/payroll-frequency-method/page2.jpg", caption: "Page 2 of 4." },
          { image: "assets/tutorials/day3/payroll-frequency-method/page3.jpg", caption: "Page 3 of 4." },
          { image: "assets/tutorials/day3/payroll-frequency-method/page4.jpg", caption: "Page 4 of 4." },
        ],
      },
      {
        title: "Daily Pay Method",
        steps: [
          { image: "assets/tutorials/day3/daily-pay-method/page1.jpg", caption: "Daily Pay Method — page 1 of 6." },
          { image: "assets/tutorials/day3/daily-pay-method/page2.jpg", caption: "Page 2 of 6." },
          { image: "assets/tutorials/day3/daily-pay-method/page3.jpg", caption: "Page 3 of 6." },
          { image: "assets/tutorials/day3/daily-pay-method/page4.jpg", caption: "Page 4 of 6." },
          { image: "assets/tutorials/day3/daily-pay-method/page5.jpg", caption: "Page 5 of 6." },
          { image: "assets/tutorials/day3/daily-pay-method/page6.jpg", caption: "Page 6 of 6." },
        ],
      },
      {
        title: "Maintain Payment Method",
        steps: [
          { image: "assets/tutorials/day3/maintain-payment-method/page1.jpg", caption: "Maintain Payment Method — page 1 of 3." },
          { image: "assets/tutorials/day3/maintain-payment-method/page2.jpg", caption: "Page 2 of 3." },
          { image: "assets/tutorials/day3/maintain-payment-method/page3.jpg", caption: "Page 3 of 3." },
        ],
      },
      {
        title: "Maintain Contribution",
        steps: [
          { image: "assets/tutorials/day3/maintain-contribution/page1.jpg", caption: "Maintain Contribution — page 1 of 3." },
          { image: "assets/tutorials/day3/maintain-contribution/page2.jpg", caption: "Page 2 of 3." },
          { image: "assets/tutorials/day3/maintain-contribution/page3.jpg", caption: "Page 3 of 3." },
        ],
      },
      {
        title: "Maintain Employees Opening Balance",
        steps: [
          { image: "assets/tutorials/day3/maintain-employees-opening-balance/page1.jpg", caption: "Maintain Employees Opening Balance — page 1 of 4." },
          { image: "assets/tutorials/day3/maintain-employees-opening-balance/page2.jpg", caption: "Page 2 of 4." },
          { image: "assets/tutorials/day3/maintain-employees-opening-balance/page3.jpg", caption: "Page 3 of 4." },
          { image: "assets/tutorials/day3/maintain-employees-opening-balance/page4.jpg", caption: "Page 4 of 4." },
        ],
      },
      {
        title: "Process Payroll with Overtime",
        steps: [
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page1.jpg", caption: "Add overtime hours for the pay period and let the system calculate OT pay.", explanation: "OT and commission are documented as separate guides because they're entered on different screens — don't assume one covers the other." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page2.jpg", caption: "Page 2 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page3.jpg", caption: "Page 3 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page4.jpg", caption: "Page 4 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page5.jpg", caption: "Page 5 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page6.jpg", caption: "Page 6 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page7.jpg", caption: "Page 7 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page8.jpg", caption: "Page 8 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page9.jpg", caption: "Page 9 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page10.jpg", caption: "Page 10 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page11.jpg", caption: "Page 11 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page12.jpg", caption: "Page 12 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page13.jpg", caption: "Page 13 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page14.jpg", caption: "Page 14 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page15.jpg", caption: "Page 15 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page16.jpg", caption: "Page 16 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page17.jpg", caption: "Page 17 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page18.jpg", caption: "Page 18 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page19.jpg", caption: "Page 19 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page20.jpg", caption: "Page 20 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page21.jpg", caption: "Page 21 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page22.jpg", caption: "Page 22 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page23.jpg", caption: "Page 23 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page24.jpg", caption: "Page 24 of 25." },
          { image: "assets/tutorials/day3/process-payroll-with-overtime/page25.jpg", caption: "Page 25 of 25." },
        ],
      },
      {
        title: "Process Payroll with Commission",
        steps: [
          { image: "assets/tutorials/day3/process-payroll-with-commission/page1.jpg", caption: "Add a salesperson's commission figure for this run.", explanation: "Commission processing is typically a per-run entry, not a recurring one, unless it's genuinely fixed month to month." },
          { image: "assets/tutorials/day3/process-payroll-with-commission/page2.jpg", caption: "Page 2 of 4." },
          { image: "assets/tutorials/day3/process-payroll-with-commission/page3.jpg", caption: "Page 3 of 4." },
          { image: "assets/tutorials/day3/process-payroll-with-commission/page4.jpg", caption: "Page 4 of 4." },
        ],
      },
      {
        title: "Advance Paid",
        steps: [
          { image: "assets/tutorials/day3/advance-paid/page1.jpg", caption: "Record a salary advance for an employee, to be deducted from a future run.", explanation: "Advance Paid and Bonus use different screens — a common mix-up for new hires." },
          { image: "assets/tutorials/day3/advance-paid/page2.jpg", caption: "Page 2 of 4." },
          { image: "assets/tutorials/day3/advance-paid/page3.jpg", caption: "Page 3 of 4." },
          { image: "assets/tutorials/day3/advance-paid/page4.jpg", caption: "Page 4 of 4." },
        ],
      },
      {
        title: "Bonus",
        steps: [
          { image: "assets/tutorials/day3/bonus/page1.jpg", caption: "Process a one-time bonus for select employees in this run only.", explanation: "A one-time bonus should not be set up as a recurring entry — that would repeat it into future runs unintentionally." },
          { image: "assets/tutorials/day3/bonus/page2.jpg", caption: "Page 2 of 2." },
        ],
      },
      {
        title: "Hide Bonus Process",
        steps: [
          { image: "assets/tutorials/day3/hide-bonus-process/page1.jpg", caption: "Hide Bonus Process — page 1 of 5." },
          { image: "assets/tutorials/day3/hide-bonus-process/page2.jpg", caption: "Page 2 of 5." },
          { image: "assets/tutorials/day3/hide-bonus-process/page3.jpg", caption: "Page 3 of 5." },
          { image: "assets/tutorials/day3/hide-bonus-process/page4.jpg", caption: "Page 4 of 5." },
          { image: "assets/tutorials/day3/hide-bonus-process/page5.jpg", caption: "Page 5 of 5." },
        ],
      },
      {
        title: "Recurring Payroll for Advance Paid Allowance Overtime",
        steps: [
          { image: "assets/tutorials/day3/recurring-payroll-for-advance-paid-allowance-overtime/page1.jpg", caption: "Set up a recurring entry so a stable allowance or advance auto-applies every future run.", explanation: "Saves repetitive manual entry, but should only be used for genuinely recurring items — not one-off bonuses." },
          { image: "assets/tutorials/day3/recurring-payroll-for-advance-paid-allowance-overtime/page2.jpg", caption: "Page 2 of 6." },
          { image: "assets/tutorials/day3/recurring-payroll-for-advance-paid-allowance-overtime/page3.jpg", caption: "Page 3 of 6." },
          { image: "assets/tutorials/day3/recurring-payroll-for-advance-paid-allowance-overtime/page4.jpg", caption: "Page 4 of 6." },
          { image: "assets/tutorials/day3/recurring-payroll-for-advance-paid-allowance-overtime/page5.jpg", caption: "Page 5 of 6." },
          { image: "assets/tutorials/day3/recurring-payroll-for-advance-paid-allowance-overtime/page6.jpg", caption: "Page 6 of 6." },
        ],
      },
      {
        title: "Final Payroll",
        steps: [
          { image: "assets/tutorials/day3/final-payroll/page1.jpg", caption: "Final Payroll — page 1 of 7." },
          { image: "assets/tutorials/day3/final-payroll/page2.jpg", caption: "Page 2 of 7." },
          { image: "assets/tutorials/day3/final-payroll/page3.jpg", caption: "Page 3 of 7." },
          { image: "assets/tutorials/day3/final-payroll/page4.jpg", caption: "Page 4 of 7." },
          { image: "assets/tutorials/day3/final-payroll/page5.jpg", caption: "Page 5 of 7." },
          { image: "assets/tutorials/day3/final-payroll/page6.jpg", caption: "Page 6 of 7." },
          { image: "assets/tutorials/day3/final-payroll/page7.jpg", caption: "Page 7 of 7." },
        ],
      },
      {
        title: "How to Change Payment Method After Payroll Has Been Processed",
        steps: [
          { image: "assets/tutorials/day3/how-to-change-payment-method-after-payroll-has-been-processed/page1.jpg", caption: "How to Change Payment Method After Payroll Has Been Processed — page 1 of 2." },
          { image: "assets/tutorials/day3/how-to-change-payment-method-after-payroll-has-been-processed/page2.jpg", caption: "Page 2 of 2." },
        ],
      },
      {
        title: "How to Change the Payroll Description",
        steps: [
          { image: "assets/tutorials/day3/how-to-change-the-payroll-description/page1.jpg", caption: "How to Change the Payroll Description — page 1 of 2." },
          { image: "assets/tutorials/day3/how-to-change-the-payroll-description/page2.jpg", caption: "Page 2 of 2." },
        ],
      },
    ],
    practiceTask: "Process a full monthly payroll run for the demo employee that includes overtime and a bonus, then set up a recurring advance entry.",
  },
  4: {
    topic: "Statutory & Compliance",
    goal: "The new hire can handle statutory contribution setup and monthly government submissions.",
    lessons: [
      {
        title: "Where to Change The Employee Employer EPF Rate",
        steps: [
          { image: "assets/tutorials/day4/where-to-change-the-employee-employer-epf-rate/page1.jpg", caption: "Locate and update an employee's EPF contribution rate.", explanation: "Getting this wrong before the first payroll run means every subsequent EPF figure needs correcting and possibly resubmitting." },
          { image: "assets/tutorials/day4/where-to-change-the-employee-employer-epf-rate/page2.jpg", caption: "Page 2 of 4." },
          { image: "assets/tutorials/day4/where-to-change-the-employee-employer-epf-rate/page3.jpg", caption: "Page 3 of 4." },
          { image: "assets/tutorials/day4/where-to-change-the-employee-employer-epf-rate/page4.jpg", caption: "Page 4 of 4." },
        ],
      },
      {
        title: "Foreign Worker EPF",
        steps: [
          { image: "assets/tutorials/day4/foreign-worker-epf/page1.jpg", caption: "Apply the foreign-worker EPF rule/rate on a non-Malaysian employee's record.", explanation: "Foreign workers may be subject to different EPF rules than local employees — this is the first thing to check if a foreign worker's contribution looks off." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page2.jpg", caption: "Page 2 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page3.jpg", caption: "Page 3 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page4.jpg", caption: "Page 4 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page5.jpg", caption: "Page 5 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page6.jpg", caption: "Page 6 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page7.jpg", caption: "Page 7 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page8.jpg", caption: "Page 8 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page9.jpg", caption: "Page 9 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page10.jpg", caption: "Page 10 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page11.jpg", caption: "Page 11 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page12.jpg", caption: "Page 12 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page13.jpg", caption: "Page 13 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page14.jpg", caption: "Page 14 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page15.jpg", caption: "Page 15 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page16.jpg", caption: "Page 16 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page17.jpg", caption: "Page 17 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page18.jpg", caption: "Page 18 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page19.jpg", caption: "Page 19 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page20.jpg", caption: "Page 20 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page21.jpg", caption: "Page 21 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page22.jpg", caption: "Page 22 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page23.jpg", caption: "Page 23 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page24.jpg", caption: "Page 24 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page25.jpg", caption: "Page 25 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page26.jpg", caption: "Page 26 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page27.jpg", caption: "Page 27 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page28.jpg", caption: "Page 28 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page29.jpg", caption: "Page 29 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page30.jpg", caption: "Page 30 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page31.jpg", caption: "Page 31 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page32.jpg", caption: "Page 32 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page33.jpg", caption: "Page 33 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page34.jpg", caption: "Page 34 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page35.jpg", caption: "Page 35 of 36." },
          { image: "assets/tutorials/day4/foreign-worker-epf/page36.jpg", caption: "Page 36 of 36." },
        ],
      },
      {
        title: "How to Get The Text File for Monthly Online Submission",
        steps: [
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page1.jpg", caption: "Generate the combined statutory text file covering EPF, SOCSO, EIS, and PCB for the period.", explanation: "Confirm every employee's contribution figures are finalized before generating this file — a rejected submission is often a data issue, not a system issue." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page2.jpg", caption: "Page 2 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page3.jpg", caption: "Page 3 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page4.jpg", caption: "Page 4 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page5.jpg", caption: "Page 5 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page6.jpg", caption: "Page 6 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page7.jpg", caption: "Page 7 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page8.jpg", caption: "Page 8 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page9.jpg", caption: "Page 9 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page10.jpg", caption: "Page 10 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page11.jpg", caption: "Page 11 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page12.jpg", caption: "Page 12 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page13.jpg", caption: "Page 13 of 14." },
          { image: "assets/tutorials/day4/how-to-get-the-text-file-for-monthly-online-submission/page14.jpg", caption: "Page 14 of 14." },
        ],
      },
      {
        title: "CP38",
        steps: [
          { image: "assets/tutorials/day4/cp38/page1.jpg", caption: "Set up a CP38 additional tax deduction instruction for a specific employee.", explanation: "CP38 is a specific instruction from LHDN for one employee, separate from the regular monthly PCB deduction." },
          { image: "assets/tutorials/day4/cp38/page2.jpg", caption: "Page 2 of 3." },
          { image: "assets/tutorials/day4/cp38/page3.jpg", caption: "Page 3 of 3." },
        ],
      },
      {
        title: "PCB CP38 Receipt No and Date",
        steps: [
          { image: "assets/tutorials/day4/pcb-cp38-receipt-no-and-date/page1.jpg", caption: "PCB CP38 Receipt No and Date — page 1 of 3." },
          { image: "assets/tutorials/day4/pcb-cp38-receipt-no-and-date/page2.jpg", caption: "Page 2 of 3." },
          { image: "assets/tutorials/day4/pcb-cp38-receipt-no-and-date/page3.jpg", caption: "Page 3 of 3." },
        ],
      },
      {
        title: "Submit CP39 to E PCB Plus E Data PCB",
        steps: [
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page1.jpg", caption: "Submit the monthly PCB data via E-PCB Plus (E Data PCB) — this is the CP39 process.", explanation: "CP39 and CP38 are often confused — CP39 is the submission process, CP38 is a specific deduction instruction." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page2.jpg", caption: "Page 2 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page3.jpg", caption: "Page 3 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page4.jpg", caption: "Page 4 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page5.jpg", caption: "Page 5 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page6.jpg", caption: "Page 6 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page7.jpg", caption: "Page 7 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page8.jpg", caption: "Page 8 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page9.jpg", caption: "Page 9 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page10.jpg", caption: "Page 10 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page11.jpg", caption: "Page 11 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page12.jpg", caption: "Page 12 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page13.jpg", caption: "Page 13 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page14.jpg", caption: "Page 14 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page15.jpg", caption: "Page 15 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page16.jpg", caption: "Page 16 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page17.jpg", caption: "Page 17 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page18.jpg", caption: "Page 18 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page19.jpg", caption: "Page 19 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page20.jpg", caption: "Page 20 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page21.jpg", caption: "Page 21 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page22.jpg", caption: "Page 22 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page23.jpg", caption: "Page 23 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page24.jpg", caption: "Page 24 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page25.jpg", caption: "Page 25 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page26.jpg", caption: "Page 26 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page27.jpg", caption: "Page 27 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page28.jpg", caption: "Page 28 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page29.jpg", caption: "Page 29 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page30.jpg", caption: "Page 30 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page31.jpg", caption: "Page 31 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page32.jpg", caption: "Page 32 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page33.jpg", caption: "Page 33 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page34.jpg", caption: "Page 34 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page35.jpg", caption: "Page 35 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page36.jpg", caption: "Page 36 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page37.jpg", caption: "Page 37 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page38.jpg", caption: "Page 38 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page39.jpg", caption: "Page 39 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page40.jpg", caption: "Page 40 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page41.jpg", caption: "Page 41 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page42.jpg", caption: "Page 42 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page43.jpg", caption: "Page 43 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page44.jpg", caption: "Page 44 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page45.jpg", caption: "Page 45 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page46.jpg", caption: "Page 46 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page47.jpg", caption: "Page 47 of 48." },
          { image: "assets/tutorials/day4/submit-cp39-to-e-pcb-plus-e-data-pcb/page48.jpg", caption: "Page 48 of 48." },
        ],
      },
      {
        title: "How to Process Payroll for Resigned Staff After Resign Date",
        steps: [
          { image: "assets/tutorials/day4/how-to-process-payroll-for-resigned-staff-after-resign-date/page1.jpg", caption: "How to Process Payroll for Resigned Staff After Resign Date — page 1 of 3." },
          { image: "assets/tutorials/day4/how-to-process-payroll-for-resigned-staff-after-resign-date/page2.jpg", caption: "Page 2 of 3." },
          { image: "assets/tutorials/day4/how-to-process-payroll-for-resigned-staff-after-resign-date/page3.jpg", caption: "Page 3 of 3." },
        ],
      },
      {
        title: "Recurring Zakat in Maintain Employee",
        steps: [
          { image: "assets/tutorials/day4/recurring-zakat-in-maintain-employee/page1.jpg", caption: "Recurring Zakat in Maintain Employee — page 1 of 3." },
          { image: "assets/tutorials/day4/recurring-zakat-in-maintain-employee/page2.jpg", caption: "Page 2 of 3." },
          { image: "assets/tutorials/day4/recurring-zakat-in-maintain-employee/page3.jpg", caption: "Page 3 of 3." },
        ],
      },
      {
        title: "Zakat and Tabung Haji",
        steps: [
          { image: "assets/tutorials/day4/zakat-and-tabung-haji/page1.jpg", caption: "Zakat and Tabung Haji — page 1 of 8." },
          { image: "assets/tutorials/day4/zakat-and-tabung-haji/page2.jpg", caption: "Page 2 of 8." },
          { image: "assets/tutorials/day4/zakat-and-tabung-haji/page3.jpg", caption: "Page 3 of 8." },
          { image: "assets/tutorials/day4/zakat-and-tabung-haji/page4.jpg", caption: "Page 4 of 8." },
          { image: "assets/tutorials/day4/zakat-and-tabung-haji/page5.jpg", caption: "Page 5 of 8." },
          { image: "assets/tutorials/day4/zakat-and-tabung-haji/page6.jpg", caption: "Page 6 of 8." },
          { image: "assets/tutorials/day4/zakat-and-tabung-haji/page7.jpg", caption: "Page 7 of 8." },
          { image: "assets/tutorials/day4/zakat-and-tabung-haji/page8.jpg", caption: "Page 8 of 8." },
        ],
      },
    ],
    practiceTask: "Generate the monthly statutory text file (EPF/SOCSO/EIS/PCB), set up a CP38 deduction, and process a foreign worker's EPF contribution.",
  },
  5: {
    topic: "Reports, Tools & Troubleshooting",
    goal: "The new hire can produce standard reports and use the module's supporting tools, and consolidates the whole week.",
    lessons: [
      {
        title: "Print EA Form",
        steps: [
          { image: "assets/tutorials/day5/print-ea-form/page1.jpg", caption: "Print an EA form for an employee, pulling from their full year of processed payroll.", explanation: "If totals look wrong, check whether every payroll run for the year was actually processed and included." },
          { image: "assets/tutorials/day5/print-ea-form/page2.jpg", caption: "Page 2 of 3." },
          { image: "assets/tutorials/day5/print-ea-form/page3.jpg", caption: "Page 3 of 3." },
        ],
      },
      {
        title: "Employee Login",
        steps: [
          { image: "assets/tutorials/day5/employee-login/page1.jpg", caption: "Employee Login — page 1 of 2." },
          { image: "assets/tutorials/day5/employee-login/page2.jpg", caption: "Page 2 of 2." },
        ],
      },
      {
        title: "Tax Benefit",
        steps: [
          { image: "assets/tutorials/day5/tax-benefit/page1.jpg", caption: "Tax Benefit — page 1 of 10." },
          { image: "assets/tutorials/day5/tax-benefit/page2.jpg", caption: "Page 2 of 10." },
          { image: "assets/tutorials/day5/tax-benefit/page3.jpg", caption: "Page 3 of 10." },
          { image: "assets/tutorials/day5/tax-benefit/page4.jpg", caption: "Page 4 of 10." },
          { image: "assets/tutorials/day5/tax-benefit/page5.jpg", caption: "Page 5 of 10." },
          { image: "assets/tutorials/day5/tax-benefit/page6.jpg", caption: "Page 6 of 10." },
          { image: "assets/tutorials/day5/tax-benefit/page7.jpg", caption: "Page 7 of 10." },
          { image: "assets/tutorials/day5/tax-benefit/page8.jpg", caption: "Page 8 of 10." },
          { image: "assets/tutorials/day5/tax-benefit/page9.jpg", caption: "Page 9 of 10." },
          { image: "assets/tutorials/day5/tax-benefit/page10.jpg", caption: "Page 10 of 10." },
        ],
      },
      {
        title: "SQL View",
        steps: [
          { image: "assets/tutorials/day5/sql-view/page1.jpg", caption: "Build a custom query against payroll data for a report not covered by a standard printout.", explanation: "SQL View is for cases where the default reports don't cover what a client needs — some familiarity with querying helps here." },
          { image: "assets/tutorials/day5/sql-view/page2.jpg", caption: "Page 2 of 4." },
          { image: "assets/tutorials/day5/sql-view/page3.jpg", caption: "Page 3 of 4." },
          { image: "assets/tutorials/day5/sql-view/page4.jpg", caption: "Page 4 of 4." },
        ],
      },
      {
        title: "Online Mobile Approval",
        steps: [
          { image: "assets/tutorials/day5/online-mobile-approval/page1.jpg", caption: "Online Mobile Approval — page 1 of 9." },
          { image: "assets/tutorials/day5/online-mobile-approval/page2.jpg", caption: "Page 2 of 9." },
          { image: "assets/tutorials/day5/online-mobile-approval/page3.jpg", caption: "Page 3 of 9." },
          { image: "assets/tutorials/day5/online-mobile-approval/page4.jpg", caption: "Page 4 of 9." },
          { image: "assets/tutorials/day5/online-mobile-approval/page5.jpg", caption: "Page 5 of 9." },
          { image: "assets/tutorials/day5/online-mobile-approval/page6.jpg", caption: "Page 6 of 9." },
          { image: "assets/tutorials/day5/online-mobile-approval/page7.jpg", caption: "Page 7 of 9." },
          { image: "assets/tutorials/day5/online-mobile-approval/page8.jpg", caption: "Page 8 of 9." },
          { image: "assets/tutorials/day5/online-mobile-approval/page9.jpg", caption: "Page 9 of 9." },
        ],
      },
      {
        title: "Batch Email Email Client Batch and SMTP Batch",
        steps: [
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page1.jpg", caption: "Batch-send payslips to multiple employees at once, choosing Email Client Batch or SMTP Batch.", explanation: "If an employee says they never got their payslip, check whether the batch send actually succeeded for that specific address first." },
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page2.jpg", caption: "Page 2 of 12." },
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page3.jpg", caption: "Page 3 of 12." },
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page4.jpg", caption: "Page 4 of 12." },
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page5.jpg", caption: "Page 5 of 12." },
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page6.jpg", caption: "Page 6 of 12." },
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page7.jpg", caption: "Page 7 of 12." },
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page8.jpg", caption: "Page 8 of 12." },
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page9.jpg", caption: "Page 9 of 12." },
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page10.jpg", caption: "Page 10 of 12." },
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page11.jpg", caption: "Page 11 of 12." },
          { image: "assets/tutorials/day5/batch-email-email-client-batch-and-smtp-batch/page12.jpg", caption: "Page 12 of 12." },
        ],
      },
      {
        title: "Comparison the Precious Month Payroll Data for Each Employees",
        steps: [
          { image: "assets/tutorials/day5/comparison-the-precious-month-payroll-data-for-each-employees/page1.jpg", caption: "Run the month-over-month payroll comparison report to spot unusual changes before approving a run.", explanation: "Useful for catching anomalies (e.g. a wage change that shouldn't be there) before a client escalates it as a bug." },
          { image: "assets/tutorials/day5/comparison-the-precious-month-payroll-data-for-each-employees/page2.jpg", caption: "Page 2 of 3." },
          { image: "assets/tutorials/day5/comparison-the-precious-month-payroll-data-for-each-employees/page3.jpg", caption: "Page 3 of 3." },
        ],
      },
    ],
    practiceTask: "Print an EA form for the demo employee, run a month-over-month payroll comparison report, and batch-email payslips. Afternoon: shadow a real support ticket or call with a senior teammate, and freely re-browse the Knowledge Base for anything unclear before the evaluation.",
  },
};
